In [ ]:
#uv add pandas

In [1]:
print("Hi")

Hi

In [3]:
import pandas as pd

df = pd.read_csv("./data/Food_Delivery_Times.csv")
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [8]:
df.columns

Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')

In [10]:
df.shape

(1000, 9)

In [11]:
df = df.dropna()
df.shape

(883, 9)

In [12]:
categorical_cols = ["Weather", "Traffic_Level" , "Vehicle_Type" , "Time_of_Day"]
for col in categorical_cols:
    print(f"Unique values in {col}: {df[col].unique()}")

Unique values in Weather: <StringArray>
['Windy', 'Clear', 'Foggy', 'Rainy', 'Snowy']
Length: 5, dtype: str
Unique values in Traffic_Level: <StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str
Unique values in Vehicle_Type: <StringArray>
['Scooter', 'Bike', 'Car']
Length: 3, dtype: str
Unique values in Time_of_Day: <StringArray>
['Afternoon', 'Evening', 'Night', 'Morning']
Length: 4, dtype: str

In [14]:
df

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68
...,...,...,...,...,...,...,...,...,...
995,107,8.50,Clear,High,Evening,Car,13,3.0,54
996,271,16.28,Rainy,Low,Morning,Scooter,8,9.0,71
997,861,15.62,Snowy,High,Evening,Scooter,26,2.0,81
998,436,14.17,Clear,Low,Afternoon,Bike,8,0.0,55
999,103,6.63,Foggy,Low,Night,Scooter,24,3.0,58

In [18]:
#preprocessing
df_new = pd.get_dummies(df, columns=categorical_cols)
df_new.head()

,Order_ID,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min,Weather_Clear,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Windy,Traffic_Level_High,Traffic_Level_Low,Traffic_Level_Medium,Vehicle_Type_Bike,Vehicle_Type_Car,Vehicle_Type_Scooter,Time_of_Day_Afternoon,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night
0,522,7.93,12,1.0,43,False,False,False,False,True,False,True,False,False,False,True,True,False,False,False
1,738,16.42,20,2.0,84,True,False,False,False,False,False,False,True,True,False,False,False,True,False,False
2,741,9.52,28,1.0,59,False,True,False,False,False,False,True,False,False,False,True,False,False,False,True
3,661,7.44,5,1.0,37,False,False,True,False,False,False,False,True,False,False,True,True,False,False,False
4,412,19.03,16,5.0,68,True,False,False,False,False,False,True,False,True,False,False,False,False,True,False

In [19]:
df_new.shape

(883, 20)

In [21]:
df_new.describe()

,Order_ID,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
count,883.000000,883.000000,883.000000,883.000000,883.000000
mean,508.109853,10.051586,17.019253,4.639864,56.425821
std,287.925161,5.688582,7.260201,2.922172,21.568482
min,1.000000,0.590000,5.000000,0.000000,8.000000
25%,263.500000,5.130000,11.000000,2.000000,41.000000
50%,512.000000,10.280000,17.000000,5.000000,55.000000
75%,758.500000,15.025000,23.000000,7.000000,71.000000
max,1000.000000,19.990000,29.000000,9.000000,141.000000

In [22]:
#uv add scikit-learn

In [25]:
df_new.columns

Index(['Order_ID', 'Distance_km', 'Preparation_Time_min',
       'Courier_Experience_yrs', 'Delivery_Time_min', 'Weather_Clear',
       'Weather_Foggy', 'Weather_Rainy', 'Weather_Snowy', 'Weather_Windy',
       'Traffic_Level_High', 'Traffic_Level_Low', 'Traffic_Level_Medium',
       'Vehicle_Type_Bike', 'Vehicle_Type_Car', 'Vehicle_Type_Scooter',
       'Time_of_Day_Afternoon', 'Time_of_Day_Evening', 'Time_of_Day_Morning',
       'Time_of_Day_Night'],
      dtype='str')

In [ ]:
#train and test split

In [31]:
X_test.shape

(221, 19)

In [32]:
y_test.shape

(221,)

In [84]:
# Linear Regression

from sklearn.linear_model import LinearRegression
# min max normalization
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

def train_regression_model(df , cols):
    df_new = df[cols].copy()
    X = df_new.drop("Delivery_Time_min", axis=1)
    y = df_new["Delivery_Time_min"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
    
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    model = LinearRegression()
    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)
  

    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)   
    # print(f"Mean Squared Error: {mse}")
    # print(f"R^2 Score: {r2}")
    #adjuested R2 score
    n = X_test_scaled.shape[0]  # number of samples
    p = X_test_scaled.shape[1]  # number of features
    adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)
    # print(f"Adjusted R^2 Score: {adjusted_r2}")
    
    return model, adjusted_r2

In [44]:
df.columns

Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')

In [45]:
train_regression_model(df_new, df_new.columns)

Mean Squared Error: 66.92698948844969
R^2 Score: 0.8418410808360208
Adjusted R^2 Score: 0.8268907352434058

(LinearRegression(), 0.8268907352434058)

In [46]:
train_regression_model(df_new, ["Distance_km", "Delivery_Time_min"])

Mean Squared Error: 150.03471026932448
R^2 Score: 0.6454445688555535
Adjusted R^2 Score: 0.6438255942841176

(LinearRegression(), 0.6438255942841176)

In [47]:
train_regression_model(df_new, ["Distance_km", 'Preparation_Time_min' , "Delivery_Time_min"])

Mean Squared Error: 91.42829708904024
R^2 Score: 0.7839406678960013
Adjusted R^2 Score: 0.7819584721886251

(LinearRegression(), 0.7819584721886251)

In [48]:
train_regression_model(df_new, ["Distance_km", 'Preparation_Time_min' ,'Courier_Experience_yrs' , "Delivery_Time_min"])

Mean Squared Error: 91.64421940038595
R^2 Score: 0.7834304097826923
Adjusted R^2 Score: 0.7804363601483516

(LinearRegression(), 0.7804363601483516)

In [61]:
my_cols = list(set(df_new.columns) - set(["Order_ID" , 'Time_of_Day_Night',
 'Time_of_Day_Morning','Time_of_Day_Evening','Time_of_Day_Afternoon']))

In [62]:
my_cols

['Weather_Rainy',
 'Traffic_Level_Medium',
 'Traffic_Level_High',
 'Vehicle_Type_Car',
 'Traffic_Level_Low',
 'Delivery_Time_min',
 'Weather_Foggy',
 'Weather_Windy',
 'Vehicle_Type_Bike',
 'Distance_km',
 'Vehicle_Type_Scooter',
 'Courier_Experience_yrs',
 'Preparation_Time_min',
 'Weather_Clear',
 'Weather_Snowy']

In [63]:
train_regression_model(df_new, my_cols)

Mean Squared Error: 66.40264273128642
R^2 Score: 0.8430801940400354
Adjusted R^2 Score: 0.8324157412078048

(LinearRegression(), 0.8324157412078048)

In [65]:
import itertools
all_feature_columns = set(df_new.columns) - set(["Delivery_Time_min"])

In [79]:
## feature selection
len(list(itertools.combinations(all_feature_columns, 11)))

75582

In [82]:
column_selection = []

for i in range(1, 20):
    column_selection += list(itertools.combinations(all_feature_columns, i))

print(len(column_selection))

524287

In [ ]:
best_r2 = -float("inf")
best_model = None
best_cols = None
for cols in column_selection:
    model, r2 = train_regression_model(df_new, list(cols) + ["Delivery_Time_min"])

    if r2 > best_r2:
        best_r2 = r2
        best_model = model
        best_cols = cols

        print(f"New best R^2 Score: {best_r2}")
        print(f"New best columns: {best_cols}")

print(f"Best R^2 Score: {best_r2}")
print(f"Best columns: {best_cols}")

New best R^2 Score: -0.06297325001096787
New best columns: ('Time_of_Day_Afternoon',)
New best R^2 Score: -0.05516551394796365
New best columns: ('Weather_Rainy',)
New best R^2 Score: -0.054677007629261754
New best columns: ('Time_of_Day_Evening',)
New best R^2 Score: -0.00333464845659015
New best columns: ('Traffic_Level_High',)
New best R^2 Score: 0.006195298860979692
New best columns: ('Traffic_Level_Low',)
New best R^2 Score: 0.6438255942841176
New best columns: ('Distance_km',)
New best R^2 Score: 0.645937936849691
New best columns: ('Weather_Rainy', 'Distance_km')
New best R^2 Score: 0.6794978264785578
New best columns: ('Traffic_Level_Low', 'Distance_km')
New best R^2 Score: 0.7819584721886251
New best columns: ('Distance_km', 'Preparation_Time_min')
New best R^2 Score: 0.7834828869986838
New best columns: ('Weather_Rainy', 'Distance_km', 'Preparation_Time_min')
New best R^2 Score: 0.7898705302023636
New best columns: ('Traffic_Level_High', 'Distance_km', 'Preparation_Time_min')
New best R^2 Score: 0.8120130678463962
New best columns: ('Traffic_Level_Low', 'Distance_km', 'Preparation_Time_min')
New best R^2 Score: 0.814417798797178
New best columns: ('Weather_Rainy', 'Traffic_Level_Low', 'Distance_km', 'Preparation_Time_min')
New best R^2 Score: 0.8288829163763476
New best columns: ('Traffic_Level_Low', 'Distance_km', 'Weather_Snowy', 'Preparation_Time_min')
New best R^2 Score: 0.8313802283543199
New best columns: ('Traffic_Level_Low', 'Distance_km', 'Preparation_Time_min', 'Weather_Clear')
New best R^2 Score: 0.8346586165545843
New best columns: ('Weather_Rainy', 'Traffic_Level_Low', 'Distance_km', 'Weather_Snowy', 'Preparation_Time_min')
New best R^2 Score: 0.8390732608670834
New best columns: ('Traffic_Level_Low', 'Distance_km', 'Weather_Snowy', 'Preparation_Time_min', 'Weather_Clear')
New best R^2 Score: 0.8440613508238037
New best columns: ('Weather_Rainy', 'Traffic_Level_Low', 'Distance_km', 'Weather_Snowy', 'Weather_Foggy', 'Preparation_Time_min')
New best R^2 Score: 0.8451722901318004
New best columns: ('Weather_Rainy', 'Traffic_Level_Low', 'Distance_km', 'Weather_Snowy', 'Weather_Foggy', 'Vehicle_Type_Scooter', 'Preparation_Time_min')